title: Abderaouf KHELFAOUI
description: >
  Master’s student in Data Science and AI at the University of Lille,
  with an engineering background in automation, control, and robotics.
  Passionate about intelligent systems, reinforcement learning, and
  autonomous mobile robots. Sharing projects, research notes, and
  experiments across AI and robotics.

baseurl: "/monday"
url: ""
permalink: ':title/'
blog_theme: dark

# Profile information
name: Abderaouf KHELFAOUI
tagline: Data Science & AI Student
about-description: >
  Former engineering student in automation and control, now pursuing a
  Master’s degree in Data Science and AI at the University of Lille.
  Experienced in ROS2, Gazebo, reinforcement learning, and multi-robot
  systems. Interested in bringing intelligent behavior into real robots
  through AI and advanced control.

pic: profile.jpg   # Replace with your image in /assets/img/

# Contact links
email: abderaouf@gmail.com
phone: 0660606660
website: Abderaouf-KHELFAOUI.github.io
linkedin: Abderaouf KHELFAOUI
github: Abderaouf KHELFAOUI
twitter: NOx

# Tracker
analytics:

# Comments
discus-identifier:

# Important settings
assets:
  sources:
    - assets/fonts
    - assets/img
    - assets/js
    - assets/stylesheets

# Build settings
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md

gems:
  - jekyll-feed
  - jekyll-assets

include: [_pages]
